init:
  - git config --global core.autocrlf true
environment:
  matrix:
    - nodejs_version: "4.2.2"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install
  - npm install gulp -g
test_script:
  - npm test
build: off
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json